name: Build And Test

on: 
 push: 
  branches: [ main ]
 pull_request:
  branches: [ main ]
jobs: 
 build-test:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v4
   - name: Use Node.js 20
     uses: actions/setup-node@v4
     with: 
       node-version: 20
   - name: Mocha issue fix
     run: npm install --save-dev mocha
   - name: Install the dependencies
     run: npm install
   - name: Test the code
     run: npm test
 deploy:
  runs-on: ubuntu-latest
  needs: build-test
  steps:
  - name: Deploy to production
    uses: johnbeynon/render-deploy-action@v0.0.8
    with:
      api-key: ${{secrets.API_TOKEN_RENDER_BABE}}
      service-id: ${{secrets.SERVICE_ID}}
      wait-for-success: true
