name: Build And Test

on: 
 push: 
  branches: [ main ]
 pull_request:
  branches: [ main ]
jobs: 
 build-test:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v4
   - name: Use Node.js 20
     uses: actions/setup-node@v4
     with: 
       node-version: 20
   - name: Install the dependencies
     run: npm install
   - name: Test the code
     run: npm test
